### ISSUE TITLE
Dlaczego opierasz się na pracy innych

### ISSUE THREAD

**Issue by legacy6vz** [Wuukong/ClyeBOT#1]
Publikujesz czyjąś prace, i dodatkowo nazywasz się Devem przez to... Brak RIGCZu, tyle powiem

**Comment by Wuukong** [comment]
nie wiem o co ci chodzi, jesteś hejterem i mnie obrażasz. Naura

**Comment by legacy6vz** [comment]
Polecam nauczyć się odróżniać Hejt od krytyki. Kradniesz czyiś kod i dajesz jakoś swój. Zastanów się naprawdę...
